- quelpa.el
- test/quelpa-test.el
This change tries removing existing recipes, then adds the installed one.
> Implement suggestion from #69

- quelpa.el
tried to clean up the `quelpa` function a bit, hopefully everything still works. can you check? thx
> refactor cache update into function

- README.md
- ci/.emacs
- ci/run.sh
- quelpa.el
- test/quelpa-test.el
Work in progress, obviously don't merge.
So a few disclaimers:
- primarily opened for discussion, as someone new to emacs, lisp and elisp, I have no idea what I'm doing, so I don't really expect this to work.
- if eventually good enough to merge, the commits will all be squashed into one with an appropriate commit message. these commit messages are just temporary.
So regarding the hashes. I'm thinking just have a hash of the concatenated hashes of all the relevant files (using `quelpa-check-file-hash`)? Where "relevant files" are by default all the .el files (recursively)? (Or otherwise can be changed with the `:files` in the recipe.)
I guess the hardest part is getting the version number to prepend to the hash? Possible to just check each relevant file for a `;; Version:` header, and …
> [WIP] fetch local directory as a package for url fetcher

- README.md
- quelpa.el
- test/quelpa-test.el
- world-domination.org
Ref <https://github.com/melpa/melpa/pull/3569>.
Ref <https://github.com/melpa/melpa/issues/3570>.
> update to new melpa github url

- README.md
- quelpa.el
> Ensure test for checking out MELPA works

- quelpa.el
to install with the file fetcher
This happened because `package-build--expand-source-file-list` does not
expand directory listings (under :files in a recipe) into its contents
(i.e. its filenames), which was the original assumption.
This meant that `package-build--slurp-file` would attempt to
`insert-file-contents` on a directory, hence causing the (example)
error:
Quelpa: failed to checkout `nyan-mode': `Read error: is a directory,
/home/u/sc/el/nyan-mode/img'
The fix here is to replace any directory listings that
`package-build--expand-source-file-list` gives into its contents (i.e. a
list of filenames located in the directory) recursively.
`quelpa-expand-source-file-list` is the new function that does this,
with `quelpa-directory-files` being a recursive helper function to
traverse the …
> fix: packages with directories under :files spec in their recipes fail

- quelpa.el
> Following the move of package-build.el

- quelpa.el
> use melpa dir for recipes

- README.md
> Mention GNU Tar for MacOS users

- README.md
- quelpa.el
> add option to control automatic self-upgrade

- README.md
* Expanded OS X section slightly.
* Homebrew is just asking to get owned, so if it must stay then let's
offer a more decent alternative (with little things like OpenPGP
verifiable code sources ...
* Which brings us to the addition of MacPorts.
* Also, yes the two systems really did name them differently.
* Left out Fink and the other one because no one really uses them
much.
> GNU Tarred and Feathered

- README.md
- bootstrap.el
- ci/.emacs
- quelpa.el
- test/quelpa-test.el
renamed all `package-build-` to `quelpa-build-`, seems to work in my test already. all the fetchers that were removed are back. need to strip out stuff and clean it up still
> integrate package-build from commit 940c991

- quelpa.el
This is a refactored PR from #150.
In this change:
- Make `quelpa` works with Windows 10 built-in tar. Windows 10 tar is bsdtar, and it works without converting path to cygwin.
- Allow `quelpa` to be able to shallow clone a remote with depth `quelpa-git-clone-depth`.
> Add support for bsdtar, git-clone depth

- README.md
- quelpa.el
> Add: (quelpa-upgrade-all)

- quelpa.el
This is a refactored PR from #152 
In this change:
- Change from `git reset --hard` to `git checkout` so we don't accidentally lose commit when trying to test local change not committed.
> Use "git checkout" instead of "git reset" when checkout git tip

- quelpa.el
This should be merged after #162 
- Allow to force upgrade by using prefix in `quelpa-upgrade-all` or `quelpa-upgrade`. The default is to signal error whenever there's local change left. With force option, always upgrade to latest ref and signal no error.
- Allow to upgrade package from current local ref. This is done by `C-u C-u M-x quelpa-upgrade`.
> Allow to force upgrade or upgrade from local ref of git

- README.org
- quelpa.el
This should fix #169 
Now, old packages will be automatically removed when newer one is installed.
> feat: auto clean obsoleted package after install new ones

- quelpa.el
Currently README says quelpa supports Emacs 25 and higher.
Update `Package-Requires:` to Emacs 25.1.
This PR make CI lint quiet a bit.
> Update emacs version

- quelpa.el
- test/quelpa-test.el
> quelpa-version-cmp: also consider pre/alpha/beta/snapshot version checking

- quelpa.el
Fix #205 
The builtin `package-installed-p` is considering `nil` `min-version` as `(0 0)`, thus compare it with prerelease version of `tablegen-mode` will return `nil`, as the prerelease version has version of `(0 -1)`.
We patch it by considering nil `min-version` as `quelpa--min-ver`
> quelpa-update: patch package-installed-p to consider nil min-version as smallest possible version

- README.org
- quelpa.el
> quelpa-git-clone-partial: check version berfore doing partial clone

- .github/workflows/test.yml
- .gitignore
- Eask
> test: Figure out why build fails
