- quelpa.el
- test/quelpa-test.el
package-build seems to its namespace with the commit below:
https://github.com/milkypostman/melpa/commit/91914339caa19b4d52a20678e61ad07ed7819a70
So, quelpa shoud change its call for package-build.
> replace pb/ to package-build--.

- quelpa.el
I got following byte-compile warning.
```
In quelpa-expand-recipe:
quelpa.el:544:14:Warning: called-interactively-p called with 0 arguments, but
requires 1
```
> Fix byte-compile warning

- quelpa.el
so the last change didn't fix the problem :)
I thought it would be cleaner anyway to just mess with `package-install-file` on windows and leave it alone on other systems regardless of it fixing the problem with recentf or not. hence this change now
> use original package-install-file for non-windows

- .travis.yml
- ci/run.sh
I've noticed that the Travis build failed me on my other PR, it looks as if it's the previously used PPA is no longer working properly, so I've changed the relevant files to use a newer one and pull in a stable Emacs 24.5 (as the other PPA does *not* provide it).  There also seem to be problems with the packages built in the integration tests, but I'll address that in another PR.
> Fix CI PPA

- ci/.emacs
Affected packages:
- nav (Google code is no more, replaced by 2048-game)
- furl (moved to github and git, replaced by latex-pretty-symbols)
- confluence (moved to sf)
- mediawiki (no longer bzr, replaced with color-theme)
> Fix integration tests

- quelpa.el
Previously quelpa would only complete package names based on files in
`~/.emacs.d/quelpa/melpa/recipes`.  This changes makes it offer all
recipe names found in any of the `quelpa-melpa-recipe-stores`
directories.
> Complete recipe names from all recipe stores

- quelpa.el
This allows dependencies to be installed manually via another
means before running Quelpa.
> Only attempt to install requirements that aren’t already installed.

- README.md
- ci/.emacs
- quelpa.el
upstream `package-build` has removed the wiki fetcher hence we do the same
> remove wiki bzr cvs darcs fossil svn support

- README.org
- quelpa.el
This patch adds the function `quelpa-upgrade-all-maybe` and the variable
`quelpa-upgrade-interval`.
`quelpa-upgrade-all-maybe` will call `quelpa-upgrade-all` if either the
timestamp-file doesn't exist or the timestamp file's modification time is more
than `quelpa-upgrade-interval` days in the past. After that the modification
time of the timestamp-file is updated.
I have refrained from using the following functions to keep compatibility with
Emacs 24:
* `file-attribute-modification-time` was introduced around 26.1. – I used `(nth
5 (file-attributes timestamp))` instead.
* `time-to-days` was introduced around 25.1. – I used `time-to-seconds` instead.
I'm not sure if I got the prefix stuff right. I've never used it and copied the solution from stackoverflow.
> Add quelpa-upgrade-all-maybe – upgrade every X days

- .editorconfig
- README.org
- quelpa.el
- test/quelpa-test.el
Allow `quelpa` to install recipe from `quelpa-cache` as preferred recipe. It helps smooth user experience when both installing and updating package, just using `M-x quelpa` and user can install/updating packages from both MELPA and custom cached recipes.
This tackle #163 mentioned issue, which allow `M-x quelpa` to be able to view both cached recipes and stores.
Another aspect of issue in #163 is for `M-x quelpa-upgrade` to be able to only seeing installed packages, instead of all cached recipes like now. This change also fixes that behavior.
This will make #155 deprecated, since the final goal of it is also the same, just using different approach, and likely requires user configuration changes since it introduces new mode.
After this change, the enlightened scenarios will be:
- User be …
> Allow quelpa to also install recipe from quelpa-cache

- quelpa.el
Support for emacs-27, since it's not need to call `package-initialize` anymore in user init file.
We will need to call `package-load-all-descriptors` for `package-alist` to be properly set.
Also, change some part to `when-let`, which is emacs-25 macro, since this change is very small, I slip this into previous change altogether.
> emacs-27: Load package descriptors if package.el is not initialized

- README.org
- quelpa.el
Implement the behavior discussed in #169 
1. Have an option to allow user to silently delete obsoleted packages when update to newer one.
2. `quelpa-upgrade-all`, `quelpa-upgrade`, `C-u M-x quelpa` will try to delete obsoleted packages while respecting 1.
3. `quelpa` by default will default not delete obsoleted packages while respecting 1.
> Adding setting to prevent obsoleted package to be deleted

- quelpa.el
Dont' show package deleted message when deleting obsoleted packages.
User can still check for those from `*Message*` buffer.
This fix issue 2 in #176
> Don't show package deleted message

- README.org
- quelpa.el
Add `github-ssh` fetcher that will conveniently  fetch from ssh link of github.
> feat: add github-ssh fetcher

- quelpa.el
Emacs 27 support quick start, normally the `package-quickstart-refresh` will be called by `package-install`, so it's fine for Quelap.
However, in case of we trying to upgrade the same package version, there's case that the quick start information is staled, `Quelpa` should call `package-quickstart-refresh` explicitly at that time.
> fix: call quickstart-refresh when build package failed

- quelpa.el
- test/quelpa-test.el
This addresses #186 
With this, for local development, when local ref upgrade is triggered (`C-u C-u M-x quelpa-upgrade`), it will properly upgrade the package to local ref version, **regardless of installed version**.
This is only case where we allow upgrade (or downgrage?) to lower version.
This PR will provide a very convenient method to test with changes in development package. We can just use local ref upgrade without having to commit the changes.
> quelpa-upgrade: allow to install current ref regardless of installed version

- quelpa.el
I found `M-x quelpa` doesn't show single chacacter packages such as `@` and `a`.
```elisp
(seq-difference
(cl-loop
for store in quelpa-melpa-recipe-stores
if (stringp store)
;; this regexp matches all files except dotfiles
append (directory-files store nil "^[^.].*$")
else if (listp store)
append store)
(cl-loop
for store in quelpa-melpa-recipe-stores
if (stringp store)
;; this regexp matches all files except dotfiles
append (directory-files store nil "^[^.].+$")
else if (listp store)
append store))
;; => ("@" "a" "f" "s")
```
> fix regexp for single character package

- .github/workflows/test.yml
Add CI for newly released emacs 27.1
> ci: add emacs 27.1 to CI target

- quelpa.el
`Quelpa` is installing package using `package-install-file`, which will not trigger `package-quickstart-refresh` like in `package-install`.
Although `package.el` can probably fix it, for now `Quelpa` should explicitly refresh quickstart after installed package.
> quelpa-build: always refresh quickstart db

- quelpa.el
- test/quelpa-test.el
Fix #200 
- MELPA recipes are prioritized over temporary recipe defined with `M-x quelpa`.
- User would not accidentally update package by using `quelpa`
- Temporary recipe defined with `M-x quelpa` that's not in MELPA is still being installable via `M-x quelpa`
Also:
- Fix `quelpa-interactive-candidate` to use `assoc-string` so the recipe from stores (which is list of string) will be properly selected.
> quelpa: prioritize recipe-stores over quelpa-cache

- quelpa.el
I think the version should be `1.0`? Since the latest release tag is `v1.0`, see https://github.com/quelpa/quelpa/releases.
> Bump version to 1.0?

- README.org
I assumed all source should be indented by 2 by default?
> Fixed indentation in README.

- quelpa.el
With the recommendation of setting `quelpa-update-melpa-p` to `nil` when loading Quelpa, MELPA store can go out-of-sync with the latest one.
Currently we have to manually set back `quelpa-update-melpa-p` to `t` and trigger Quelpa again to update it.
This PR provide another way of updating MELPA store while still having `quelpa-update-melpa-p` to `nil` by invoke `quelap-checkout-melpa` interactively (via `M-x`).
When calling `quelpa-checkout-melpa` normally, the `quelpa-update-melpa-p` is still respected.
> quelpa-checkout-melpa: make it as command and update MELPA when call interactively

- quelpa.el
Some defcustoms are nullable, so set the their types as such to prevent type mismatch errors from showing in customization.
> Fix defcustom types

- README.org
- quelpa.el
Fix #214 
Switch to use partial clone instead of shallow clone for more developer friendly.
See https://github.com/quelpa/quelpa/issues/214#issuecomment-798011842
> quelpa-git: switch default from shallow clone to partial clone for git recipes

- README.org
- quelpa.el
Problem:
When `quelpa` is combined with `use-package-quelpa`, configuring the defcustom `quelpa-autoremove-p` will have no effect when the recipe does not explicitly supply the `:autoremove` keyword. This unintuitive and inconsistent behavior was introduced in #175, this PR fixes this issue.
> Use quelpa-autoremove-p when no prefix given

- quelpa.el
Under Windows, the `insert-file-contentts` is used, however, it has a side-effect of modifying buffer content and leading to a user prompt of killing buffer or not. This is quite annoying, especially when setting up a new machine with a lot of `quelpa`  calls to install packages.
There's no easy way to avoid the prompt since the function invokes `kill-buffer` directly.
This fix is to address that issue, ignore the unreal buffer modifying and let `quelpa` continue to run without waiting.
> quelpa-package-install-file: dont ask when kill buffer

- quelpa.el
It seems the default value of the `:files` field in the Melpa receipe format was recently updated.
I just copied it from the [Melpa README](https://github.com/melpa/melpa#recipe-format).
> Updating :files default value

- quelpa.el
When `quelpa-build-explicit-tar-format-p` is set to non-nil, `--format=gnu` is appended (as expected).
But this would results in an error if the system is using `bsdtar`, whose `--format` option doesn't recognize `gnu`.
This commit make sure `--format=gnu` is added only for `gnu-tar`.
> check tar-type before appending --format=gnu

- README.org
- quelpa.el
Support `elpa-devel` version if `:version-type elpa` is specified in the package recipe.
The version scheme is: `<package-version-with-atleast-3-segs>.YYYYMMDD.HHMMSS`.
For example: `(vertico :fetcher github :repo "minad/vertico" :files (:defaults "extensions/*.el") :version-type elpa)` will create a package like `vertico-0.27.0.20220914.164819`
> Support elpa-devel versioning scheme with :version-type elpa

- quelpa.el
Fixes https://github.com/quelpa/quelpa/issues/233
> [fix] Defensive programming when (e.g.) `url-copy-file` returns a malformed Emacs package

- quelpa.el
- test/quelpa-test.el
Create the version list first and convert it back to a string to make sure that the version string will always be in the correct format.
Until now, some versions like `1.2.3pre ` will be joined innocently with the time stamp of `123.2312` to become `1.2.3pre.123.2312` which is not a correct version format.
This change fixes that so the string version will become `1.2.3pre123.2312` which is a correctly formated one.
> quelpa-build: correctly append date time version to elpa version

- quelpa.el
quelpa-checkout will return nil, and there will be an exception.
Signed-off-by: Schspa Shi <schspa@gmail.com>
> quelpa-build: fix error when there is no need to build

- quelpa.el
- test/quelpa-test.el
This will close #247.
I've added a missing test for Gitlab. CI seems kinda fucked, but tests do pass for Emacs 26.3 and 27.1
> Add more git forges

- quelpa.el
fixes: https://github.com/quelpa/quelpa/issues/257
Tested on Gentoo ~amd64, with Git 2.48.0 and TERM="xterm-256color" exported in the environment.
> prevent Git from hanging up with TERM in the env

- .github/workflows/test.yml
- quelpa.el
The test env is run without adequate `TERM` set so `git` and `hg` log is hang with
```
Test quelpa-hg-async condition:
(error "Command ’(env LC_ALL=C /usr/bin/timeout -k 60 600 hg paths)’ exited with non-zero status 124: WARNING: terminal is not fully functional\15\nPress RETURN to continue error in exit handlers:\
```
This set the `TERM` env so the test can pass.
Also, fix ci warning of obsoleted `if/when-let` in latest Emacs
> ci: fix test by set TERM for test env
